name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v2  # Cambiado a v2
        with:
          command: buildozer android debug
          workdir: kivy_de_tu_calculadora
          user: root  # Especificar usuario root que existe en el contenedor

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-apk-${{ steps.get-date.outputs.date }}
          path: kivy_de_tu_calculadora/bin/*.apk
